### ISSUE TITLE
Deprecated Pypi latest version (not present UAH currency for RU language)

### ISSUE THREAD

**Issue by banchinche** [savoirfairelinux/num2words#440] opened 2022-02-09 09:11 UTC
Pypi latest version is not actual to source code. I really need UAH-currency for RU language. [This commit](https://github.com/savoirfairelinux/num2words/commit/ca5989a3ec9d7f13abbbc51f192afe8909f51422) and [tests](https://github.com/savoirfairelinux/num2words/commit/40ab739f6c384fb5b8c27c59eac1e5d75cf08c69) tell that it is already implemented.

Executable code example
```
from num2words import num2words


if __name__ == '__main__':
    number: float = 126.52
    print(num2words(number=number, lang='ru', to='currency', currency='UAH'))
```

Expected behavior
```
сто двадцать шесть гривен, пятьдесят две копейки
```
Result
```
KeyError: 'UAH'
raise NotImplementedError(
NotImplementedError: Currency code "UAH" not implemented for "Num2Word_RU"
```

**Comment by mrodriguezg1991** [comment] 2022-08-19 19:25
@banchinche hello , a new version of the library was deployed 0.5.12 , can you verified if the issue is fix ?
Let me know in order to close this issue 
Thanks

**Comment by smilingDima** [comment] 2023-04-18 10:34
Yes, it been fixed.

**Closed** 2023-04-18 13:24 UTC
