### ISSUE TITLE
Latvian num2words ...how to fix?

### ISSUE THREAD

**Issue by MatissJekabsons** [savoirfairelinux/num2words#142] opened 2017-12-03 11:27 UTC
### Expected Behaviour

Kopā: EUR 1.21
Summa vārdos: Viens Eiro un Divdesmit Viens cents

### Actual Behaviour

Kopā: EUR 1.21
Summa vārdos: Viens Eiros un Divdesmit Viens cents

### Steps to reproduce

* Make an invoice for customer with latvian language
* Print an invoice for this customer

For now i found only this one issue, that there is one unneeded letter "s" 
Is it possible to write word Euros without s in the end? As i understood, then this is default Odoo translation in Odoo core?

Bes regards and Thx for yor time.

**Comment by shulcsm** [comment] 2017-12-05 08:51
Can't reproduce. Probably something to do with odoo or old version.
num2words==0.5.6
```
>>> from num2words import num2words
>>> num2words(1.21, lang='lv', to='currency')
'viens eiro, divdesmit viens cents'
```

**Comment by erozqba** [comment] 2018-01-06 04:59
@MatissJekabsons could you verify if it works OK with the latest version of num2words?

**Comment by mrodriguezg1991** [comment] 2022-08-03 20:31
@MatissJekabsons is his still an issue or we can close it?

**Closed** 2022-08-19 21:54 UTC
